# Generated by Django 4.2.5 on 2023-09-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_bet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='apAway',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='apHome',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='goalAway',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='goalHome',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='shotsAway',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='shotsHome',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
    ]
