# Generated by Django 4.2.5 on 2023-11-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_bet', '0002_jogo_apaway_jogo_aphome_jogo_goalaway_jogo_goalhome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='cornerAway',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='cornerHome',
            field=models.BigIntegerField(default=0),
        ),
    ]
