# Generated by Django 4.2.5 on 2023-11-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_bet', '0007_alter_jogo_date_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='date_game',
            field=models.DateField(default='21-11-2023'),
        ),
    ]
