# Generated by Django 4.2.5 on 2023-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robo_bet', '0011_alter_jogo_date_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=60)),
                ('goalHomeFinal', models.BigIntegerField(default=0)),
                ('away', models.CharField(max_length=60)),
                ('goalAwayFinal', models.BigIntegerField(default=0)),
                ('apHomeFinal', models.BigIntegerField(default=0)),
                ('apAwayFinal', models.BigIntegerField(default=0)),
                ('shotsHomeFinal', models.BigIntegerField(default=0)),
                ('shotsAwayFinal', models.BigIntegerField(default=0)),
                ('cornerHomeFinal', models.BigIntegerField(default=0)),
                ('cornerAwayFinal', models.BigIntegerField(default=0)),
            ],
        ),
    ]
